services:
  app:
    build:
      context: ./flashcards
    container_name: flashcards-backend
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - '8080:8080'
  db:
    image: postgres:15.1-alpine
    container_name: postgres-flashcards
    command: postgres -c log_statement=all
    ports:
      - "2525:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    volumes:
      - ./flashcards/src/main/resources/db-init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
  web:
    build: ./flashcards-frontend
    ports:
      - "3000:3000"
    restart: always

volumes:
  db-data:
